package EMSApp;

/**
* EMSApp/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Shonibare/eclipse-workspace/EMS_Project_CORBA/src/ServerInterface.idl
* Sunday, 5 April 2020 14:12:26 o'clock WAT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public EMSApp.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (EMSApp.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EMSApp.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EMSApp.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EMSApp.ServerInterfaceHelper.type ();
  }

}
