package EMSApp;


/**
* EMSApp/ServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Shonibare/eclipse-workspace/EMS_Project_CORBA/src/ServerInterface.idl
* Sunday, 5 April 2020 14:12:26 o'clock WAT
*/

abstract public class ServerInterfaceHelper
{
  private static String  _id = "IDL:EMSApp/ServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, EMSApp.ServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EMSApp.ServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EMSApp.ServerInterfaceHelper.id (), "ServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EMSApp.ServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EMSApp.ServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EMSApp.ServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EMSApp.ServerInterface)
      return (EMSApp.ServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EMSApp._ServerInterfaceStub stub = new EMSApp._ServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EMSApp.ServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EMSApp.ServerInterface)
      return (EMSApp.ServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EMSApp._ServerInterfaceStub stub = new EMSApp._ServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
