package FrontEndApp;


/**
* FrontEndApp/FrontEndInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Shonibare/eclipse-workspace/COMP6231_PROJECT/src/FrontEndInterface
* Sunday, 12 April 2020 18:57:34 o'clock WAT
*/

public interface FrontEndInterface extends FrontEndInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndInterface
