package DEMSBase;


/**
* DEMSBase/EventList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public final class EventList implements org.omg.CORBA.portable.IDLEntity
{
  public DEMSBase.Event list[] = null;
  public int total = (int)0;

  public EventList ()
  {
  } // ctor

  public EventList (DEMSBase.Event[] _list, int _total)
  {
    list = _list;
    total = _total;
  } // ctor

} // class EventList
