package DEMSBase;


/**
* DEMSBase/EventTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

abstract public class EventTypeHelper
{
  private static String  _id = "IDL:DEMSBase/EventType:1.0";

  public static void insert (org.omg.CORBA.Any a, DEMSBase.EventType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DEMSBase.EventType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (DEMSBase.EventTypeHelper.id (), "EventType", new String[] { "Conference", "TradeShow", "Seminar"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DEMSBase.EventType read (org.omg.CORBA.portable.InputStream istream)
  {
    return DEMSBase.EventType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DEMSBase.EventType value)
  {
    ostream.write_long (value.value ());
  }

}
