package DEMSBase;

/**
* DEMSBase/EventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public final class EventHolder implements org.omg.CORBA.portable.Streamable
{
  public DEMSBase.Event value = null;

  public EventHolder ()
  {
  }

  public EventHolder (DEMSBase.Event initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DEMSBase.EventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DEMSBase.EventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DEMSBase.EventHelper.type ();
  }

}
