package DEMSBase;


/**
* DEMSBase/EventListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

abstract public class EventListHelper
{
  private static String  _id = "IDL:DEMSBase/EventList:1.0";

  public static void insert (org.omg.CORBA.Any a, DEMSBase.EventList that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DEMSBase.EventList extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = DEMSBase.EventHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (DEMSBase.LIST_SIZE.value, _tcOf_members0 );
          _members0[0] = new org.omg.CORBA.StructMember (
            "list",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "total",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DEMSBase.EventListHelper.id (), "EventList", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DEMSBase.EventList read (org.omg.CORBA.portable.InputStream istream)
  {
    DEMSBase.EventList value = new DEMSBase.EventList ();
    value.list = new DEMSBase.Event[DEMSBase.LIST_SIZE.value];
    for (int _o0 = 0;_o0 < (DEMSBase.LIST_SIZE.value); ++_o0)
    {
      value.list[_o0] = DEMSBase.EventHelper.read (istream);
    }
    value.total = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DEMSBase.EventList value)
  {
    if (value.list.length != (DEMSBase.LIST_SIZE.value))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (DEMSBase.LIST_SIZE.value); ++_i0)
    {
      DEMSBase.EventHelper.write (ostream, value.list[_i0]);
    }
    ostream.write_long (value.total);
  }

}
