package DEMSBase;


/**
* DEMSBase/LIST_SIZE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public interface LIST_SIZE
{
  public static final int value = (int)(2048);
}
