package InterfaceApp;


/**
* InterfaceApp/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Monday, April 13, 2020 10:18:36 AM PDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
