package InterfaceApp;


/**
* InterfaceApp/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Monday, April 13, 2020 10:18:36 AM PDT
*/

public interface ServerInterfaceOperations 
{
  String addEvent (String eventType, String eventID, int bookingCapacity);
  String removeEvent (String eventType, String eventID);
  String bookEvent (String customerID, String eventID, String eventType);
  String cancelEvent (String customerID, String eventID, String eventType);
  String getBookingSchedule (String customerID);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  String listEventAvailability (String eventType);
} // interface ServerInterfaceOperations
