package InterfaceApp;

/**
* InterfaceApp/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Monday, April 13, 2020 10:18:36 AM PDT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public InterfaceApp.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (InterfaceApp.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterfaceApp.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterfaceApp.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterfaceApp.ServerInterfaceHelper.type ();
  }

}
