package DEMSBase;

/**
* DEMSBase/DEMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public final class DEMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DEMSBase.DEMS value = null;

  public DEMSHolder ()
  {
  }

  public DEMSHolder (DEMSBase.DEMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DEMSBase.DEMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DEMSBase.DEMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DEMSBase.DEMSHelper.type ();
  }

}
