package DEMSBase;


/**
* DEMSBase/EventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public class EventType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static DEMSBase.EventType[] __array = new DEMSBase.EventType [__size];

  public static final int _Conference = 0;
  public static final DEMSBase.EventType Conference = new DEMSBase.EventType(_Conference);
  public static final int _TradeShow = 1;
  public static final DEMSBase.EventType TradeShow = new DEMSBase.EventType(_TradeShow);
  public static final int _Seminar = 2;
  public static final DEMSBase.EventType Seminar = new DEMSBase.EventType(_Seminar);

  public int value ()
  {
    return __value;
  }

  public static DEMSBase.EventType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected EventType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class EventType
