package DEMSBase;


/**
* DEMSBase/Event.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

public final class Event implements org.omg.CORBA.portable.IDLEntity
{
  public String ID = null;
  public DEMSBase.EventType Type = null;
  public int Capacity = (int)0;
  public int TotalBooked = (int)0;

  public Event ()
  {
  } // ctor

  public Event (String _ID, DEMSBase.EventType _Type, int _Capacity, int _TotalBooked)
  {
    ID = _ID;
    Type = _Type;
    Capacity = _Capacity;
    TotalBooked = _TotalBooked;
  } // ctor

} // class Event
