package DEMSBase;


/**
* DEMSBase/EventHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMSInterface.idl
* Sunday, March 1, 2020 10:16:59 PM PST
*/

abstract public class EventHelper
{
  private static String  _id = "IDL:DEMSBase/Event:1.0";

  public static void insert (org.omg.CORBA.Any a, DEMSBase.Event that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DEMSBase.Event extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "ID",
            _tcOf_members0,
            null);
          _tcOf_members0 = DEMSBase.EventTypeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "Type",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "Capacity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "TotalBooked",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DEMSBase.EventHelper.id (), "Event", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DEMSBase.Event read (org.omg.CORBA.portable.InputStream istream)
  {
    DEMSBase.Event value = new DEMSBase.Event ();
    value.ID = istream.read_string ();
    value.Type = DEMSBase.EventTypeHelper.read (istream);
    value.Capacity = istream.read_long ();
    value.TotalBooked = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DEMSBase.Event value)
  {
    ostream.write_string (value.ID);
    DEMSBase.EventTypeHelper.write (ostream, value.Type);
    ostream.write_long (value.Capacity);
    ostream.write_long (value.TotalBooked);
  }

}
