package EMSApp;


/**
* EMSApp/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Shonibare/eclipse-workspace/EMS_Project_CORBA/src/ServerInterface.idl
* Sunday, 5 April 2020 14:12:26 o'clock WAT
*/

public interface ServerInterfaceOperations 
{
  String addEvent (String managerId, String eventId, String eventType, int capacity);
  String removeEvent (String managerId, String eventId, String eventType);
  String listEventAvailability (String eventType);
  String bookEvent (String customerId, String eventId, String eventType);
  String cancelEvent (String customerId, String eventId, String evenType);
  String getBookingSchedule (String customerId);
  String swapEvent (String customerId, String newEventId, String newEventType, String oldEventId, String oldEventType);
  void shutdown ();
} // interface ServerInterfaceOperations
